### ISSUE TITLE
Incorrect temperature displayed when updating weather using GadgetBridge

### ISSUE THREAD

**Issue by SSSzat** [SSSzat/InfiniTime#1]
### Verification

- [X] I searched for similar bug reports (including closed issues) and found none was relevant.

### What happened?

When the phone was displaying 25 degrees, the watch shows 20 degrees.

### What should happen instead?

The watch should show the same temperature as the phone

### Reproduction steps

Install InfiniTime 1.13, select PineTimeStyle, enable weather.
Install GadgetBridge, install TWFG, enable weather integration.
Refresh Weather.
Check temperature displayed on your phone
Check temperature displayed on your watch
Be disappointed they don't match.

### More details?

I'm opening this issue because I'm not sure what the right solution is and it's entirely possible I've misunderstood something.

Currently, on each weather refresh, GB delivers 2 temperature values to the watch, the first is the current temperature with an expiry time of 6h, the 2nd is called 24h forecast, has an expiry of 24h, and is generated by adding the daily high and low temperatures together then dividing by 2, to give an average(ish) temperature for the day. Details [here](https://codeberg.org/Freeyourgadget/Gadgetbridge/src/commit/cc9c8d4207f746d5df79f62ca7b90f2d624a30fe/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/pinetime/PineTimeJFSupport.java#L753-L804)

The issue is that the watch has no way to know which of these 2 temperature values to pick, so it does so at random, more often than not it displays the wrong value.

My first instinct is to simply remove the 24h forecast from the data GB delivers to the watch, via a PR against GB to remove lines 779-804 of the above file. This means we will only have 1 temperature value in the timeline per timestamp which should mean that the watch shows the same current temperature as the phone. Hopefully we can then work towards handling longer forecast data by creating multiple events with separate timestamps and expiries so the temperature updates even without new data being supplied, but in the short term the temperature should display something somewhat valid for 6h, and if new data is received that will be displayed instead.

We could modify the getCurrentTemperature function to pick the entry which has a shorter expiry time, but that feels like working around the issue rather than fixing it. Whatever the solution we probably need to also modify this function to handle overlapping entries (if GB sends a 6h forecast every hour for example)

### Version

1.13

### Companion app

Gadgetbridge

**Comment by shengqishi666** [comment]
GB向手表提供了两个温度值：第一个是当前温度，有效期为6小时；第二个被称为24小时预报，有效期为24小时。

需要注意的是，这两个有效期是相当随意的，因为GB目前并没有通过WeatherSpec获取这些信息。这可以向GB开发者提出，作为一种潜在的改进建议。

24小时预报是通过将日最高温和最低温相加然后除以2来生成的，从而得出一个平均的日温。

这可以拆分成两个不同的值，使得最小值/最大值的计算更加可预测。但目前尚不清楚这些数据推送的频率，可能会消耗过多内存。

我的第一反应是通过对GB的PR（Pull Request）来移除手表接收的24小时预报数据，具体来说是移除上述文件的第779-804行。

然而，没有保证GB会接收到其他WeatherSpec。这可能导致忽略唯一可用的天气数据。

我们可以修改getCurrentTemperature函数，选择有效期较短的条目，但这感觉像是在绕过问题而不是解决它。

设计的初衷是时间线可以包含相同类型数据的重复条目。选择有效期更短的数据可能在大多数情况下会更好，但不能保证总是正确。

另一个选择是忽略PTS表盘中的长期预报。其他组件可能仍然希望显示它，可能需要更多的文字/解释。

**Comment by shengqishi666** [comment]
手表最初显示的温度是正确的，但过了一段时间后，温度变成了20度。

这是因为较短时效的预报过期了，而配套设备未能发送新的预报数据。因此，设备回退到显示每日平均温度。
